### ISSUE TITLE
Allow input files from stdin

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#17]
This is not important , but for simple use, if might be nice to allow the command-line crossmap script to allow stdin as an input files (by convention this is usually done as e.g. `-i -` rather than `-i filename.csv`). For example, I have a dublin core file with species names as one of the lines, and I was thinking I would pass it through a simple perl script to pick out the names and feed them into crossmap. It's slightly more elegant if I can do this in a single pipeline, rather than having to save to intermediate files.

I only mention it as this is usually allowed by default by most command-line parsing libraries (e.g. argparse in python - I'm not familiar with ruby). So I'm surprised that it doesn't just come "for free" in crossmap.

**Comment by dimus** [comment]
yes, definitely a good idea, I'll investigate opt parsing library I use, and may be switch to other one if it does not support stdin

**Comment by dimus** [comment]
@hyanwong, I released 0.2.0 version with stdin and stdout support. If you can try it and give a feedback -- would be great
