### ISSUE TITLE
Allow chaining of crossmap instances

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#18]
I have been trying to chain crossmap instance together, to look up synonyms using CoL, then look up the returned (accepted) name from another provider (e.g. EoL / OpenTree / whatever). I do this using the acceptedName from the first call as the scientificName for the second. 

However, this requires changing the column names between instances, so that `acceptedName` of one instance is treated as the `scientificName` of another (and also to change the output names so that the input fields in the first command aren't taken as input for the second command).

At the moment I'm switching the names using a simple perl regexp substitution (and blatting the scientificName fields in the initial input):

```
cat names.csv | crossmap -i - -o - | perl -pe 's/scientificName/input/g; s/acceptedName/scientificName/' | crossmap -i - -o -d 179
```

but perhaps if this is a use case that might see more general usage, it might be worth having a switch which allows this sort of relabelling automatically?

**Comment by hyanwong** [comment]
There are 2 things that need to be done for this: (1) make sure that none of the input fields (apart from taxonID) are fed into the next chained command (2) read the acceptedName output as a scientificName input.

**Comment by hyanwong** [comment]
For (1), it seems not unreasonable to have a switch which says "don't re-output the input fields, apart from taxonID".

**Comment by dimus** [comment]
I can imagine several use cases for chaining them crossmaps. For example someone might want to run unmatched names against another database, or recheck matched names against other source. Implementing such usecases would make program's api more complex and less "unixy". However all of these approaches could benefit from removing supplied input (except taxonID). So may be a solution would be to 

* make a switch to leave only taxonID from original input
* add wikipage to show possible scenarios

**Comment by hyanwong** [comment]
Seems like a good first step.

I would like one of the fields to the the "best name" returned my the match - i.e. the acceptedName if this is a synonym, or the matched name if this is not a synonym (see https://github.com/GlobalNamesArchitecture/gn_crossmap/issues/19). Otherwise it is rather difficult to code up this sort of logic in a simple sed pipeline. Is there any reason why acceptedName shouldn't simply contain the matched name if this is a valid (non-synonym) scientific name?
