### ISSUE TITLE
acceptedName omitted from output if not a synonym

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#19]
for example

`echo -e "taxonID,scientificName\n1,Acanthurus chirurgus" | crossmap -i - -o - -d 1`

gives

```
1,Acanthurus chirurgus,Canonical form exact match,Acanthurus chirurgus,"Acanthurus chirurgus (Bloch, 1787)",Acanthurus chirurgus,species,species,,,0,0.988,26846886
1,Acanthurus chirurgus,Canonical form exact match,Acanthurus chirurgus,"Acanthurus chirurgus (non Bloch, 1787)",Acanthurus chirurgus,species,species,synonym,"Acanthurus bahianus Castelnau, 1855
```

So the first line is missing an `acceptedName` field. In this case I would like to default to the first line, since it is not a synonym. But I can't simply do that by filtering out lines with 'synonym' and looking for the "acceptedName" field, which I would like to do.

**Comment by dimus** [comment]
yes, makes sense

**Comment by dimus** [comment]
From the point of this particular matching the following happened. In both cases names matched by canonical form, and then scoring was looking at the authorship. In first case authors were:
Linnaeus vs non Bloch --- Linnaeus is not Bloch, so we could not actually match authors, and authorship did not negatively affect the score

In second case it was Linnaeus vs Bloch --- authors did not match and the score went down.
