### ISSUE TITLE
Enable tab-separated output from crossmap

### ISSUE THREAD

**Issue by hyanwong** [GlobalNamesArchitecture/gn_crossmap#22]
Since the return values from crossmap often include commas, the output fields are often quoted strings with embedded command, making it rather tedious to parse the output without using a proper csv parser. If it were possible to get an tab-separated output, this would presumably be much easier, since non of the return fields are likely to have a tab.

So could we have a switch (or perhaps even the default) to output with tabs as separators. Or perhaps you could simply use the same separator for output as was used in the input, which would reduce the number of switches needed.

On this topic, I don't know if the absence of tabs in the return fields is guaranteed (e.g. no tabs in the matchedName), but perhaps it should be, as I can't see any use for them, and it seems sensible to replace all occurrences of lines of whitespace characters with a single, normal space.

**Comment by dimus** [comment]
makes sense, I'll add a tab flag
